# Setup
title:               "Convex Optimization in Data Science"
description:         'Convex Optimization in Data Science'
url:                 http://127.0.0.1:4000 #https://nglelinh.github.io/optimization-for-data-science-iuh-2025
baseurl:             ''
imgurl:              https://nglelinh.github.io/optimization-for-data-science-iuh-2025/img
paginate:            5
permalink:           pretty

# Multi-language support
languages:           ["en", "vi"]
default_lang:        "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# Language-specific configurations
t:
  en:
    title: "Convex Optimization in Data Science"
    description: "Convex Optimization in Data Science"
    home: "Home"
    chapters: "Chapters"
    language: "Language"
    switch_language: "Switch to Vietnamese"
  vi:
    title: "Tối ưu hóa lồi trong Khoa học Dữ liệu"
    description: "Tối ưu hóa lồi trong Khoa học Dữ liệu"
    home: "Trang chủ"
    chapters: "Các chương"
    language: "Ngôn ngữ"
    switch_language: "Chuyển sang tiếng Anh"
# About/contact
author:
  name:              Nguyen Le Linh
  email:             nglelinh@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Collections for multilingual content
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Custom vars
version:             1.1.0
markdown: kramdown

# Analytics
google_analytics_id: ""
