# Setup
title:               "Optimization in Data Science"
description:         'Optimization in Data Science'
url:                 https://nglelinh.github.io
baseurl:             '/optimization-for-data-science-iuh-2025'
imgurl:              https://nglelinh.github.io/optimization-for-data-science-iuh-2025/img
paginate:            5
permalink:           pretty

# Multi-language support
languages:           ["en", "vi"]
default_lang:        "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# Language-specific configurations
t:
  en:
    title: "Optimization in Data Science"
    description: "Optimization in Data Science"
    home: "Home"
    chapters: "Chapters"
    language: "Language"
    switch_language: "Switch to Vietnamese"
    required: "Required"
    optional: "Optional"
  vi:
    title: "Tối ưu hóa trong Khoa học Dữ liệu"
    description: "Tối ưu hóa trong Khoa học Dữ liệu"
    home: "Trang chủ"
    chapters: "Các chương"
    language: "Ngôn ngữ"
    switch_language: "Chuyển sang tiếng Anh"
    required: "Bắt buộc"
    optional: "Tùy chọn"
# About/contact
author:
  name:              Nguyen Le Linh
  email:             nglelinh@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Collections for multilingual content
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Custom vars
version:             1.1.0
markdown: kramdown

# Analytics
google_analytics_id: ""
