# Setup
title:               "모두를 위한 컨벡스 최적화"
description:         '모두를 위한 컨벡스 최적화'
url:                 https://nglelinh.github.io/optimization-for-data-science-iuh-2025
baseurl:             'optimization-for-data-science-iuh-2025'
imgurl:             https://nglelinh.github.io/optimization-for-data-science-iuh-2025/img
paginate:            5
permalink:           pretty
# About/contact
author:
  name:              Kyeongmin Woo
  email:             wgm0601@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
markdown: kramdown

# Analytics
google_analytics_id: "UA-189737072-1"
