#!/usr/bin/env python3
"""
Script to translate Korean text to English in markdown files
for chapters 18-25 of the convex optimization book.
"""

import os
import re
import glob
from pathlib import Path

# Dictionary of common Korean phrases and their English translations
TRANSLATIONS = {
    # Common academic phrases
    "이번 장에서는": "In this chapter,",
    "이번 절에서는": "In this section,",
    "다음과 같이": "as follows:",
    "다음과 같다": "as follows:",
    "살펴보도록 하자": "let's examine",
    "살펴보자": "let's look at",
    "알아보자": "let's find out",
    "정리하면": "in summary,",
    "정리해보자": "let's organize",
    "확인해보자": "let's verify",
    "유도해보자": "let's derive",
    "구해보자": "let's find",
    "계산해보자": "let's calculate",
    "증명해보자": "let's prove",
    "보여주자": "let's show",
    "나타내자": "let's represent",
    "정의하자": "let's define",
    "가정하자": "let's assume",
    "고려하자": "let's consider",
    "분석해보자": "let's analyze",
    "검토해보자": "let's review",
    "설명하자": "let's explain",
    "기술하자": "let's describe",
    "논의하자": "let's discuss",
    "연구하자": "let's study",
    "탐구하자": "let's explore",
    "조사하자": "let's investigate",
    
    # Mathematical terms
    "최적화": "optimization",
    "최적해": "optimal solution",
    "최적값": "optimal value",
    "최소화": "minimization",
    "최대화": "maximization",
    "제약조건": "constraint",
    "목적함수": "objective function",
    "라그랑지안": "Lagrangian",
    "듀얼": "dual",
    "프라이멀": "primal",
    "경사하강법": "gradient descent",
    "뉴턴 방법": "Newton's method",
    "수렴": "convergence",
    "발산": "divergence",
    "근사": "approximation",
    "해": "solution",
    "문제": "problem",
    "알고리즘": "algorithm",
    "방법": "method",
    "기법": "technique",
    "접근법": "approach",
    "전략": "strategy",
    "절차": "procedure",
    "과정": "process",
    "단계": "step",
    "반복": "iteration",
    "계산": "computation",
    "연산": "operation",
    "함수": "function",
    "변수": "variable",
    "매개변수": "parameter",
    "상수": "constant",
    "벡터": "vector",
    "행렬": "matrix",
    "스칼라": "scalar",
    "텐서": "tensor",
    "공간": "space",
    "집합": "set",
    "원소": "element",
    "부분집합": "subset",
    "교집합": "intersection",
    "합집합": "union",
    "차집합": "difference",
    "여집합": "complement",
    "정의역": "domain",
    "치역": "range",
    "상": "image",
    "역상": "preimage",
    "사상": "mapping",
    "변환": "transformation",
    "함수": "function",
    "관계": "relation",
    "대응": "correspondence",
    "동치": "equivalence",
    "동형": "isomorphism",
    "준동형": "homomorphism",
    "자기동형": "automorphism",
    "내적": "inner product",
    "외적": "outer product",
    "곱": "product",
    "합": "sum",
    "차": "difference",
    "몫": "quotient",
    "나머지": "remainder",
    "약수": "divisor",
    "배수": "multiple",
    "소수": "prime number",
    "합성수": "composite number",
    "자연수": "natural number",
    "정수": "integer",
    "유리수": "rational number",
    "무리수": "irrational number",
    "실수": "real number",
    "복소수": "complex number",
    "허수": "imaginary number",
    "절댓값": "absolute value",
    "크기": "magnitude",
    "길이": "length",
    "거리": "distance",
    "각도": "angle",
    "방향": "direction",
    "위치": "position",
    "좌표": "coordinate",
    "축": "axis",
    "원점": "origin",
    "기준점": "reference point",
    "중심": "center",
    "반지름": "radius",
    "지름": "diameter",
    "둘레": "perimeter",
    "넓이": "area",
    "부피": "volume",
    "높이": "height",
    "폭": "width",
    "깊이": "depth",
    "두께": "thickness",
    
    # Common expressions
    "즉": "that is,",
    "따라서": "therefore,",
    "그러므로": "thus,",
    "그런데": "however,",
    "하지만": "but,",
    "그러나": "however,",
    "또한": "also,",
    "또": "also,",
    "더욱이": "moreover,",
    "게다가": "furthermore,",
    "특히": "particularly,",
    "예를 들어": "for example,",
    "예컨대": "for instance,",
    "일반적으로": "generally,",
    "보통": "usually,",
    "대개": "typically,",
    "종종": "often,",
    "때때로": "sometimes,",
    "항상": "always,",
    "결코": "never,",
    "반드시": "necessarily,",
    "아마도": "probably,",
    "확실히": "certainly,",
    "분명히": "clearly,",
    "명백히": "obviously,",
    "당연히": "naturally,",
    "물론": "of course,",
    "실제로": "actually,",
    "사실": "in fact,",
    "결국": "eventually,",
    "마지막으로": "finally,",
    "처음에": "initially,",
    "먼저": "first,",
    "다음에": "next,",
    "그 다음": "then,",
    "이후": "after,",
    "이전": "before,",
    "동안": "during,",
    "때": "when,",
    "만약": "if,",
    "만일": "if,",
    "경우": "case,",
    "상황": "situation,",
    "조건": "condition,",
    "환경": "environment,",
    "맥락": "context,",
    "배경": "background,",
    "기반": "basis,",
    "근거": "grounds,",
    "이유": "reason,",
    "원인": "cause,",
    "결과": "result,",
    "효과": "effect,",
    "영향": "influence,",
    "관계": "relationship,",
    "연관": "association,",
    "연결": "connection,",
    "관련": "relation,",
    "대한": "about,",
    "에 대해": "about,",
    "관하여": "regarding,",
    "에 관해": "regarding,",
    "대해서": "about,",
    "에 대하여": "about,",
    "에 관하여": "regarding,",
    "에 따라": "according to,",
    "에 의해": "by,",
    "에 의하여": "by,",
    "로부터": "from,",
    "부터": "from,",
    "까지": "to,",
    "에서": "at,",
    "에": "to,",
    "로": "to,",
    "으로": "with,",
    "와": "and,",
    "과": "and,",
    "그리고": "and,",
    "또는": "or,",
    "혹은": "or,",
    "아니면": "or,",
    "만약에": "if,",
    "그렇지 않으면": "otherwise,",
    "그렇지 않다면": "otherwise,",
    "반대로": "conversely,",
    "대신": "instead,",
    "대신에": "instead,",
    "오히려": "rather,",
    "차라리": "rather,",
    "보다는": "rather than,",
    "대신": "instead of,",
    "위해": "for,",
    "위하여": "for,",
    "때문에": "because of,",
    "때문": "because,",
    "덕분에": "thanks to,",
    "덕분": "thanks to,",
    "덕에": "thanks to,",
    "으로 인해": "due to,",
    "로 인해": "due to,",
    "으로 인하여": "due to,",
    "로 인하여": "due to,",
    "의해": "by,",
    "의하여": "by,",
    "통해": "through,",
    "통하여": "through,",
    "거쳐": "through,",
    "거쳐서": "through,",
    "이용해": "using,",
    "이용하여": "using,",
    "사용해": "using,",
    "사용하여": "using,",
    "활용해": "utilizing,",
    "활용하여": "utilizing,",
    "적용해": "applying,",
    "적용하여": "applying,",
    "도입해": "introducing,",
    "도입하여": "introducing,",
    "채택해": "adopting,",
    "채택하여": "adopting,",
    "선택해": "choosing,",
    "선택하여": "choosing,",
    "결정해": "deciding,",
    "결정하여": "deciding,",
    "판단해": "judging,",
    "판단하여": "judging,",
    "평가해": "evaluating,",
    "평가하여": "evaluating,",
    "분석해": "analyzing,",
    "분석하여": "analyzing,",
    "검토해": "reviewing,",
    "검토하여": "reviewing,",
    "조사해": "investigating,",
    "조사하여": "investigating,",
    "연구해": "studying,",
    "연구하여": "studying,",
    "탐구해": "exploring,",
    "탐구하여": "exploring,",
    "관찰해": "observing,",
    "관찰하여": "observing,",
    "확인해": "confirming,",
    "확인하여": "confirming,",
    "검증해": "verifying,",
    "검증하여": "verifying,",
    "증명해": "proving,",
    "증명하여": "proving,",
    "보여": "showing,",
    "보여주어": "showing,",
    "나타내": "representing,",
    "나타내어": "representing,",
    "표현해": "expressing,",
    "표현하여": "expressing,",
    "기술해": "describing,",
    "기술하여": "describing,",
    "설명해": "explaining,",
    "설명하여": "explaining,",
    "해석해": "interpreting,",
    "해석하여": "interpreting,",
    "이해해": "understanding,",
    "이해하여": "understanding,",
    "파악해": "grasping,",
    "파악하여": "grasping,",
    "인식해": "recognizing,",
    "인식하여": "recognizing,",
    "깨달아": "realizing,",
    "깨달아서": "realizing,",
    "알아": "knowing,",
    "알아서": "knowing,",
    "배워": "learning,",
    "배워서": "learning,",
    "익혀": "learning,",
    "익혀서": "learning,",
    "습득해": "acquiring,",
    "습득하여": "acquiring,",
    "얻어": "obtaining,",
    "얻어서": "obtaining,",
    "구해": "finding,",
    "구하여": "finding,",
    "찾아": "finding,",
    "찾아서": "finding,",
    "발견해": "discovering,",
    "발견하여": "discovering,",
    "개발해": "developing,",
    "개발하여": "developing,",
    "만들어": "creating,",
    "만들어서": "creating,",
    "생성해": "generating,",
    "생성하여": "generating,",
    "형성해": "forming,",
    "형성하여": "forming,",
    "구성해": "composing,",
    "구성하여": "composing,",
    "조직해": "organizing,",
    "조직하여": "organizing,",
    "배치해": "arranging,",
    "배치하여": "arranging,",
    "정렬해": "sorting,",
    "정렬하여": "sorting,",
    "분류해": "classifying,",
    "분류하여": "classifying,",
    "구분해": "distinguishing,",
    "구분하여": "distinguishing,",
    "분리해": "separating,",
    "분리하여": "separating,",
    "나누어": "dividing,",
    "나누어서": "dividing,",
    "합쳐": "combining,",
    "합쳐서": "combining,",
    "결합해": "combining,",
    "결합하여": "combining,",
    "통합해": "integrating,",
    "통합하여": "integrating,",
    "연결해": "connecting,",
    "연결하여": "connecting,",
    "연관시켜": "associating,",
    "연관시켜서": "associating,",
    "관련시켜": "relating,",
    "관련시켜서": "relating,",
    "비교해": "comparing,",
    "비교하여": "comparing,",
    "대조해": "contrasting,",
    "대조하여": "contrasting,",
    "대비해": "contrasting,",
    "대비하여": "contrasting,",
    "구별해": "distinguishing,",
    "구별하여": "distinguishing,",
    "차별해": "differentiating,",
    "차별하여": "differentiating,",
    "변별해": "discriminating,",
    "변별하여": "discriminating,",
    "식별해": "identifying,",
    "식별하여": "identifying,",
    "인지해": "recognizing,",
    "인지하여": "recognizing,",
    "감지해": "detecting,",
    "감지하여": "detecting,",
    "탐지해": "detecting,",
    "탐지하여": "detecting,",
    "발견해": "discovering,",
    "발견하여": "discovering,",
    "찾아내": "finding out,",
    "찾아내어": "finding out,",
    "알아내": "finding out,",
    "알아내어": "finding out,",
    "밝혀내": "revealing,",
    "밝혀내어": "revealing,",
    "드러내": "revealing,",
    "드러내어": "revealing,",
    "노출시켜": "exposing,",
    "노출시켜서": "exposing,",
    "공개해": "revealing,",
    "공개하여": "revealing,",
    "발표해": "presenting,",
    "발표하여": "presenting,",
    "제시해": "presenting,",
    "제시하여": "presenting,",
    "제공해": "providing,",
    "제공하여": "providing,",
    "공급해": "supplying,",
    "공급하여": "supplying,",
    "지원해": "supporting,",
    "지원하여": "supporting,",
    "도와": "helping,",
    "도와서": "helping,",
    "돕고": "helping,",
    "도움을 주어": "helping,",
    "도움을 주어서": "helping,",
    "보조해": "assisting,",
    "보조하여": "assisting,",
    "보완해": "complementing,",
    "보완하여": "complementing,",
    "개선해": "improving,",
    "개선하여": "improving,",
    "향상시켜": "improving,",
    "향상시켜서": "improving,",
    "증진시켜": "enhancing,",
    "증진시켜서": "enhancing,",
    "강화해": "strengthening,",
    "강화하여": "strengthening,",
    "확대해": "expanding,",
    "확대하여": "expanding,",
    "확장해": "extending,",
    "확장하여": "extending,",
    "연장해": "extending,",
    "연장하여": "extending,",
    "늘려": "increasing,",
    "늘려서": "increasing,",
    "증가시켜": "increasing,",
    "증가시켜서": "increasing,",
    "줄여": "reducing,",
    "줄여서": "reducing,",
    "감소시켜": "reducing,",
    "감소시켜서": "reducing,",
    "축소해": "reducing,",
    "축소하여": "reducing,",
    "단축해": "shortening,",
    "단축하여": "shortening,",
    "압축해": "compressing,",
    "압축하여": "compressing,",
    "간소화해": "simplifying,",
    "간소화하여": "simplifying,",
    "단순화해": "simplifying,",
    "단순화하여": "simplifying,",
    "복잡화해": "complicating,",
    "복잡화하여": "complicating,",
    "정교화해": "refining,",
    "정교화하여": "refining,",
    "세분화해": "subdividing,",
    "세분화하여": "subdividing,",
    "구체화해": "specifying,",
    "구체화하여": "specifying,",
    "명확화해": "clarifying,",
    "명확화하여": "clarifying,",
    "명료화해": "clarifying,",
    "명료화하여": "clarifying,",
    "투명화해": "making transparent,",
    "투명화하여": "making transparent,",
    "공개화해": "making public,",
    "공개화하여": "making public,",
    "표준화해": "standardizing,",
    "표준화하여": "standardizing,",
    "정규화해": "normalizing,",
    "정규화하여": "normalizing,",
    "일반화해": "generalizing,",
    "일반화하여": "generalizing,",
    "특수화해": "specializing,",
    "특수화하여": "specializing,",
    "개별화해": "individualizing,",
    "개별화하여": "individualizing,",
    "맞춤화해": "customizing,",
    "맞춤화하여": "customizing,",
    "최적화해": "optimizing,",
    "최적화하여": "optimizing,",
    "최소화해": "minimizing,",
    "최소화하여": "minimizing,",
    "최대화해": "maximizing,",
    "최대화하여": "maximizing,",
    "극대화해": "maximizing,",
    "극대화하여": "maximizing,",
    "극소화해": "minimizing,",
    "극소화하여": "minimizing,",
    "안정화해": "stabilizing,",
    "안정화하여": "stabilizing,",
    "고정화해": "fixing,",
    "고정화하여": "fixing,",
    "변화시켜": "changing,",
    "변화시켜서": "changing,",
    "변경해": "changing,",
    "변경하여": "changing,",
    "수정해": "modifying,",
    "수정하여": "modifying,",
    "보정해": "correcting,",
    "보정하여": "correcting,",
    "교정해": "correcting,",
    "교정하여": "correcting,",
    "조정해": "adjusting,",
    "조정하여": "adjusting,",
    "조절해": "adjusting,",
    "조절하여": "adjusting,",
    "제어해": "controlling,",
    "제어하여": "controlling,",
    "통제해": "controlling,",
    "통제하여": "controlling,",
    "관리해": "managing,",
    "관리하여": "managing,",
    "운영해": "operating,",
    "운영하여": "operating,",
    "실행해": "executing,",
    "실행하여": "executing,",
    "수행해": "performing,",
    "수행하여": "performing,",
    "진행해": "proceeding,",
    "진행하여": "proceeding,",
    "처리해": "processing,",
    "처리하여": "processing,",
    "가공해": "processing,",
    "가공하여": "processing,",
    "변환해": "converting,",
    "변환하여": "converting,",
    "전환해": "converting,",
    "전환하여": "converting,",
    "이동해": "moving,",
    "이동하여": "moving,",
    "이전해": "moving,",
    "이전하여": "moving,",
    "전달해": "delivering,",
    "전달하여": "delivering,",
    "전송해": "transmitting,",
    "전송하여": "transmitting,",
    "송신해": "transmitting,",
    "송신하여": "transmitting,",
    "수신해": "receiving,",
    "수신하여": "receiving,",
    "받아": "receiving,",
    "받아서": "receiving,",
    "얻어": "obtaining,",
    "얻어서": "obtaining,",
    "취득해": "acquiring,",
    "취득하여": "acquiring,",
    "획득해": "acquiring,",
    "획득하여": "acquiring,",
    "확보해": "securing,",
    "확보하여": "securing,",
    "보장해": "ensuring,",
    "보장하여": "ensuring,",
    "담보해": "guaranteeing,",
    "담보하여": "guaranteeing,",
    "보증해": "guaranteeing,",
    "보증하여": "guaranteeing,",
    "약속해": "promising,",
    "약속하여": "promising,",
    "다짐해": "pledging,",
    "다짐하여": "pledging,",
    "맹세해": "swearing,",
    "맹세하여": "swearing,",
    "서약해": "pledging,",
    "서약하여": "pledging,",
    "선언해": "declaring,",
    "선언하여": "declaring,",
    "발표해": "announcing,",
    "발표하여": "announcing,",
    "공표해": "announcing,",
    "공표하여": "announcing,",
    "공지해": "notifying,",
    "공지하여": "notifying,",
    "알려": "informing,",
    "알려서": "informing,",
    "통지해": "notifying,",
    "통지하여": "notifying,",
    "고지해": "notifying,",
    "고지하여": "notifying,",
    "통보해": "notifying,",
    "통보하여": "notifying,",
    "보고해": "reporting,",
    "보고하여": "reporting,",
    "신고해": "reporting,",
    "신고하여": "reporting,",
    "신청해": "applying,",
    "신청하여": "applying,",
    "지원해": "applying,",
    "지원하여": "applying,",
    "요청해": "requesting,",
    "요청하여": "requesting,",
    "청구해": "requesting,",
    "청구하여": "requesting,",
    "요구해": "demanding,",
    "요구하여": "demanding,",
    "주장해": "claiming,",
    "주장하여": "claiming,",
    "강조해": "emphasizing,",
    "강조하여": "emphasizing,",
    "부각시켜": "highlighting,",
    "부각시켜서": "highlighting,",
    "부각해": "highlighting,",
    "부각하여": "highlighting,",
    "강조해": "emphasizing,",
    "강조하여": "emphasizing,",
    "중요시해": "emphasizing,",
    "중요시하여": "emphasizing,",
    "중시해": "valuing,",
    "중시하여": "valuing,",
    "존중해": "respecting,",
    "존중하여": "respecting,",
    "인정해": "acknowledging,",
    "인정하여": "acknowledging,",
    "승인해": "approving,",
    "승인하여": "approving,",
    "허가해": "permitting,",
    "허가하여": "permitting,",
    "허용해": "allowing,",
    "허용하여": "allowing,",
    "용인해": "tolerating,",
    "용인하여": "tolerating,",
    "수용해": "accepting,",
    "수용하여": "accepting,",
    "받아들여": "accepting,",
    "받아들여서": "accepting,",
    "채택해": "adopting,",
    "채택하여": "adopting,",
    "도입해": "introducing,",
    "도입하여": "introducing,",
    "적용해": "applying,",
    "적용하여": "applying,",
    "활용해": "utilizing,",
    "활용하여": "utilizing,",
    "이용해": "using,",
    "이용하여": "using,",
    "사용해": "using,",
    "사용하여": "using,",
    "쓰여": "being used,",
    "쓰여서": "being used,",
    "쓰이고": "being used,",
    "쓰이며": "being used,",
    "쓰이는": "being used,",
    "쓰이게": "being used,",
    "쓰이도록": "to be used,",
    "쓰이기": "being used,",
    "쓰이기를": "being used,",
    "쓰이기에": "being used,",
    "쓰이기로": "being used,",
    "쓰이기만": "only being used,",
    "쓰이기도": "also being used,",
    "쓰이기까지": "even being used,",
    "쓰이기보다": "rather than being used,",
    "쓰이기보다는": "rather than being used,",
    "쓰이기에는": "for being used,",
    "쓰이기에도": "even for being used,",
    "쓰이기조차": "even being used,",
    "쓰이기마저": "even being used,",
    "쓰이기까지도": "even being used,",
    "쓰이기는": "being used,",
    "쓰이기는커녕": "far from being used,",
    "쓰이기라도": "at least being used,",
    "쓰이기라면": "if being used,",
    "쓰이기만": "only being used,",
    "쓰이기만 하면": "if only being used,",
    "쓰이기만 해도": "even if only being used,",
    "쓰이기만 하더라도": "even if only being used,",
    "쓰이기만 한다면": "if only being used,",
    "쓰이기만 하다면": "if only being used,",
    "쓰이기만 했다면": "if only had been used,",
    "쓰이기만 했어도": "even if only had been used,",
    "쓰이기만 했더라면": "if only had been used,",
    "쓰이기만 했더라도": "even if only had been used,",
    "쓰이기만 할": "only to be used,",
    "쓰이기만 할 뿐": "only to be used,",
    "쓰이기만 할 뿐이다": "only to be used,",
    "쓰이기만 할 뿐만 아니라": "not only to be used but also,",
    "쓰이기만 할 것": "only to be used,",
    "쓰이기만 할 것이다": "only to be used,",
    "쓰이기만 할 것이 아니라": "not only to be used but,",
    "쓰이기만 할 것이 아니라면": "if not only to be used,",
    "쓰이기만 할 것이 아니라서": "because not only to be used,",
    "쓰이기만 할 것이 아니라고": "not only to be used,",
    "쓰이기만 할 것이 아니라는": "not only to be used,",
    "쓰이기만 할 것이 아니라니": "not only to be used,",
    "쓰이기만 할 것이 아니라며": "not only to be used,",
    "쓰이기만 할 것이 아니라면서": "not only to be used,",
    "쓰이기만 할 것이 아니라고 해서": "not only to be used,",
    "쓰이기만 할 것이 아니라는 것": "not only to be used,",
    "쓰이기만 할 것이 아니라니까": "not only to be used,",
    "쓰이기만 할 것이 아니라며서": "not only to be used,",
    "쓰이기만 할 것이 아니라면서도": "not only to be used,",
    "쓰이기만 할 것이 아니라고 해도": "not only to be used,",
    "쓰이기만 할 것이 아니라는 것도": "not only to be used,",
    "쓰이기만 할 것이 아니라니까도": "not only to be used,",
    "쓰이기만 할 것이 아니라며서도": "not only to be used,",
    "쓰이기만 할 것이 아니라면서까지": "not only to be used,",
    "쓰이기만 할 것이 아니라고 해서까지": "not only to be used,",
    "쓰이기만 할 것이 아니라는 것까지": "not only to be used,",
    "쓰이기만 할 것이 아니라니까까지": "not only to be used,",
    "쓰이기만 할 것이 아니라며서까지": "not only to be used,",
    "쓰이기만 할 것이 아니라면서까지도": "not only to be used,",
    "쓰이기만 할 것이 아니라고 해서까지도": "not only to be used,",
    "쓰이기만 할 것이 아니라는 것까지도": "not only to be used,",
    "쓰이기만 할 것이 아니라니까까지도": "not only to be used,",
    "쓰이기만 할 것이 아니라며서까지도": "not only to be used,",
    
    # References and citations
    "자세한 내용은": "For detailed information, see",
    "참조": "see",
    "참고": "reference",
    "참고하기 바란다": "please refer to",
    "참고하시오": "please refer to",
    "참고할 것": "refer to",
    "참고하라": "refer to",
    "참고하세요": "please refer to",
    "참고해보자": "let's refer to",
    "참고해보세요": "please refer to",
    "참고해주세요": "please refer to",
    "참고해주시기 바랍니다": "please refer to",
    "참고해주시기 바라겠습니다": "please refer to",
    "참고해주시기 바라며": "please refer to",
    "참고해주시기 바라면서": "please refer to",
    "참고해주시기 바라고": "please refer to",
    "참고해주시기 바라니": "please refer to",
    "참고해주시기 바라는": "please refer to",
    "참고해주시기 바라던": "please refer to",
    "참고해주시기 바라며서": "please refer to",
    "참고해주시기 바라면서도": "please refer to",
    "참고해주시기 바라고도": "please refer to",
    "참고해주시기 바라니까": "please refer to",
    "참고해주시기 바라는데": "please refer to",
    "참고해주시기 바라던데": "please refer to",
    "참고해주시기 바라며서도": "please refer to",
    "참고해주시기 바라면서까지": "please refer to",
    "참고해주시기 바라고까지": "please refer to",
    "참고해주시기 바라니까까지": "please refer to",
    "참고해주시기 바라는데까지": "please refer to",
    "참고해주시기 바라던데까지": "please refer to",
    "참고해주시기 바라며서까지": "please refer to",
    "참고해주시기 바라면서까지도": "please refer to",
    "참고해주시기 바라고까지도": "please refer to",
    "참고해주시기 바라니까까지도": "please refer to",
    "참고해주시기 바라는데까지도": "please refer to",
    "참고해주시기 바라던데까지도": "please refer to",
    "참고해주시기 바라며서까지도": "please refer to",
}

def has_korean_text(text):
    """Check if text contains Korean characters."""
    korean_pattern = re.compile(r'[가-힣]')
    return bool(korean_pattern.search(text))

def translate_korean_text(text):
    """Translate Korean text to English using the translation dictionary."""
    result = text
    
    # Sort by length (longest first) to avoid partial replacements
    for korean, english in sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True):
        result = result.replace(korean, english)
    
    return result

def process_markdown_file(file_path):
    """Process a single markdown file to translate Korean text."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if file contains Korean text
        if not has_korean_text(content):
            print(f"No Korean text found in {file_path}")
            return False
        
        # Translate Korean text
        translated_content = translate_korean_text(content)
        
        # Write back to file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(translated_content)
        
        print(f"Translated Korean text in {file_path}")
        return True
        
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return False

def main():
    """Main function to process all markdown files in chapters 18-25."""
    base_path = Path("/Users/nguyenlelinh/teaching/Optimization/convex-optimization-for-all.github.io/contents/en")
    
    # Process chapters 18-25
    chapters_to_process = [f"chapter{i:02d}" for i in range(18, 26)]
    
    total_files = 0
    translated_files = 0
    
    for chapter in chapters_to_process:
        chapter_path = base_path / chapter / "_posts"
        
        if not chapter_path.exists():
            print(f"Chapter directory not found: {chapter_path}")
            continue
        
        # Find all markdown files in the chapter
        md_files = list(chapter_path.glob("*.md"))
        
        print(f"\nProcessing {chapter} ({len(md_files)} files)...")
        
        for md_file in md_files:
            total_files += 1
            if process_markdown_file(md_file):
                translated_files += 1
    
    print(f"\nTranslation complete!")
    print(f"Total files processed: {total_files}")
    print(f"Files with Korean text translated: {translated_files}")
    print(f"Files without Korean text: {total_files - translated_files}")

if __name__ == "__main__":
    main()
